// Code generated by tool. DO NOT EDIT.

package genreported

import (
	"fmt"
)

// G uses fmt with no alias, the minority mapping. With skip_generated=false
// this generated file is included, so the package-wide majority alias "f"
// makes this usage inconsistent and it is reported here.
func G() {
	fmt.Println("g") // want `import "fmt" should use alias "f", not no alias`
}
