// Code generated by tool. DO NOT EDIT.

package gendefault

import (
	"fmt"
)

// G uses fmt with no alias, i.e. the minority mapping. Because this file is
// generated and skip_generated defaults to true (FR-5.7), it is excluded from
// analysis, so no inconsistency is reported anywhere in this package.
func G() {
	fmt.Println("g")
}
