package genfile_test

import (
	"go/parser"
	"go/token"
	"testing"

	"github.com/podhmo/go-importalias/internal/genfile"
)

func TestIsGenerated(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want bool
	}{
		{
			name: "marker in leading band",
			src:  "// Code generated by foo. DO NOT EDIT.\npackage p\n",
			want: true,
		},
		{
			name: "marker as package doc comment",
			src:  "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage p\n",
			want: true,
		},
		{
			name: "coexists with build constraint above",
			src:  "//go:build linux\n// +build linux\n\n// Code generated by foo. DO NOT EDIT.\n\npackage p\n",
			want: true,
		},
		{
			name: "coexists with build constraint below",
			src:  "// Code generated by foo. DO NOT EDIT.\n\n//go:build linux\n\npackage p\n",
			want: true,
		},
		{
			name: "marker in body after first non-comment line",
			src:  "package p\n\nfunc F() {\n\t// Code generated by foo. DO NOT EDIT.\n}\n",
			want: false,
		},
		{
			name: "lowercase do not edit does not match",
			src:  "// Code generated by foo. do not edit.\npackage p\n",
			want: false,
		},
		{
			name: "trailing text after marker does not match",
			src:  "// Code generated by foo. DO NOT EDIT. really\npackage p\n",
			want: false,
		},
		{
			name: "block comment marker does not match",
			src:  "/* Code generated by foo. DO NOT EDIT. */\npackage p\n",
			want: false,
		},
		{
			name: "ordinary doc comment",
			src:  "// Package p does things.\npackage p\n",
			want: false,
		},
		{
			name: "no leading comment at all",
			src:  "package p\n",
			want: false,
		},
	}

	fset := token.NewFileSet()
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			file, err := parser.ParseFile(fset, "f.go", tt.src, parser.ParseComments)
			if err != nil {
				t.Fatalf("ParseFile: %v", err)
			}
			if got := genfile.IsGenerated(file); got != tt.want {
				t.Fatalf("IsGenerated() = %v, want %v", got, tt.want)
			}
		})
	}
}
